import { StyleSheet, Dimensions } from 'react-native';

const estilos = StyleSheet.create({

  fondo:{
   flex:1,
},
 contenedor:{
    alignItems:'center',
    justifyContent:'center',
    marginTop:100,
  },
  letras:{
    fontSize:25,
    color:'black',
  },
  texto:{
    fontSize:50,
    color:'red',
  },
  input:{
    width:'80%',
    height:50,
    borderColor:'#1ea541',
    borderWidth:1.5,
    borderRadius:15,
    flex:1,
    fontSize:20,
    color:'black',
  },
  emoji:{
    width:50,
    height:50,
  },
  boton:{
    width:Dimensions.get('screen').width * 0.25,
    backgroundColor:'green',
    borderColor:'black',
    borderWidth:1.5,
    borderRadius:10,
    justifyContent:'center',
    alignItems:'center',
  },
  Ctareas:{
    flexDirection:'row',
    justifyContent:'space-between',
    gap:10,
    marginTop:10,
    paddingInline:10,
  },
  dataTasks:{
    paddingVertical:20,
    borderBottomColor:'#6f6f6f',
    borderBottomWidth:5,
    flexDirection:'row',
    justifyContent:'space-between',
    gap:20,
  },
    Abotones:{
        flexDirection:'row',
        gap:30,
    },
    picker:{
          width:'80%',
          height:40,
          borderColor:'black',
          borderWidth:3,
          borderRadius:15,
          backgroundColor:'white',
        },
    textDone:{
      fontSize:30,
      color:'#6f6f6f',
      textDecorationLine:'line-through',
    },
    botonEliminar:{
      backgroundColor:'red',
      justifyContent:'center',
      alignItems:'center',
      paddingHorizontal:15,
      borderRadius:10,
    },
    BotonE:{
      fontSize:25,
    },
});
export default estilos;
